/*
 * SPDX-License-Identifier: Apache-2.0
 * SPDX-FileCopyrightText: Copyright 2026 avatarsd LLC
 *
 * ADR-0043 Phase A — quic_transport_t tests (a consumer of the separate
 * libtracer_quic module target; configured only with LIBTRACER_WITH_QUIC):
 * length-prefix framing over a real localhost QUIC
 * connection with a self-signed dev certificate generated by
 * tools/gen-dev-cert.sh at test setup. Mirrors the tcp_test coverage the
 * framing seam shares: raw duplex, split/coalesced chunk reassembly (driven by
 * a raw msquic client — the test's hand on the stream, like tcp's
 * raw_client_t), an oversize prefix as malformed (+ connection teardown), the
 * ADR-0042 owning-delivery segment identity, backpressure drain (framing sync
 * survives exhaustion), a big frame forced through many msquic RECEIVE chunks,
 * two-node FWD end-to-end over QUIC, and a config-created `kind=quic`
 * connection. Run under TSan (setarch -R) and ASan+UBSan.
 */

#include <msquic.h>

#include <array>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <future>
#include <mutex>
#include <span>
#include <string>
#include <string_view>
#include <thread>
#include <utility>
#include <vector>

#include "libtracer/byteorder.hpp"
#include "libtracer/tlv_emit.hpp"
#include "libtracer/tracer.hpp"
#include "libtracer/transport_quic.hpp"

// The raw msquic test client crosses the same non-TSan-instrumented library
// boundary as transport_quic.cpp: restate msquic's StreamSend -> SEND_COMPLETE
// and callback-serialization happens-before edges for TSan (see the matching
// annotations + rationale in src/transport_quic.cpp). No-ops outside TSan.
#if defined(__SANITIZE_THREAD__)
#define LIBTRACER_TSAN 1
#elif defined(__has_feature)
#if __has_feature(thread_sanitizer)
#define LIBTRACER_TSAN 1
#endif
#endif
#ifdef LIBTRACER_TSAN
#include <sanitizer/tsan_interface.h>
#endif

namespace {

inline void tsan_release(void* p) {
#ifdef LIBTRACER_TSAN
    __tsan_release(p);
#else
    (void)p;
#endif
}

inline void tsan_acquire(void* p) {
#ifdef LIBTRACER_TSAN
    __tsan_acquire(p);
#else
    (void)p;
#endif
}

// RAII edge for one msquic callback invocation (the src/transport_quic.cpp
// tsan_cb_guard_t): acquire on entry, release on exit.
struct tsan_cb_guard_t {
    void* p;
    explicit tsan_cb_guard_t(void* ptr) : p(ptr) { tsan_acquire(p); }
    ~tsan_cb_guard_t() { tsan_release(p); }
};

using namespace std::chrono_literals;
using tr::graph::graph_t;
using tr::graph::path_t;
using tr::graph::role_t;
using tr::net::quic_dial_tls_t;
using tr::net::quic_transport_t;
using tr::view::view_t;
using tr::wire::opt_t;
using tr::wire::type_t;

int g_failures = 0;
void check(bool ok, std::string_view what) {
    std::printf("  [%s] %.*s\n", ok ? "PASS" : "FAIL", static_cast<int>(what.size()), what.data());
    if (!ok) ++g_failures;
}

// Dev cert paths — generated once in main() by tools/gen-dev-cert.sh.
std::string g_cert;
std::string g_key;

quic_dial_tls_t dev_tls() { return quic_dial_tls_t{.ca_file = {}, .insecure_no_verify = true}; }

// A collecting sink: frames delivered on an msquic worker thread, read from the
// test thread.
struct sink_t {
    std::mutex m;
    std::vector<std::vector<std::byte>> frames;

    void push(std::span<const std::byte> f) {
        const std::lock_guard lock(m);
        frames.emplace_back(f.begin(), f.end());
    }
    [[nodiscard]] std::size_t count() {
        const std::lock_guard lock(m);
        return frames.size();
    }
    [[nodiscard]] std::vector<std::byte> at(std::size_t i) {
        const std::lock_guard lock(m);
        return frames.at(i);
    }
    [[nodiscard]] bool wait_for_count(std::size_t n, std::chrono::milliseconds budget) {
        const auto deadline = std::chrono::steady_clock::now() + budget;
        while (count() < n) {
            if (std::chrono::steady_clock::now() > deadline) return false;
            std::this_thread::sleep_for(5ms);
        }
        return true;
    }
};

// A raw msquic client — the test's hand on the stream (the tcp raw_client_t
// role): it writes arbitrary bytes with NO framing, so prefixes can be split,
// records coalesced, and a bogus oversize prefix injected.
struct raw_quic_client_t {
    const QUIC_API_TABLE* api = nullptr;
    HQUIC reg = nullptr;
    HQUIC cfg = nullptr;
    HQUIC conn = nullptr;
    HQUIC stream = nullptr;
    bool ok = false;

    std::mutex m;
    std::condition_variable cv;
    bool handshake_done = false;
    bool handshake_ok = false;
    std::atomic<bool> shut{false};  // the server tore the connection down

    struct send_buf_t {
        QUIC_BUFFER buf{};
        std::vector<std::byte> bytes;
    };

    static QUIC_STATUS QUIC_API conn_cb(HQUIC, void* ctx, QUIC_CONNECTION_EVENT* ev) {
        auto* self = static_cast<raw_quic_client_t*>(ctx);
        const tsan_cb_guard_t guard(self);  // see src/transport_quic.cpp
        switch (ev->Type) {
            case QUIC_CONNECTION_EVENT_CONNECTED: {
                const std::lock_guard lock(self->m);
                self->handshake_done = self->handshake_ok = true;
                self->cv.notify_all();
                return QUIC_STATUS_SUCCESS;
            }
            case QUIC_CONNECTION_EVENT_SHUTDOWN_INITIATED_BY_TRANSPORT:
            case QUIC_CONNECTION_EVENT_SHUTDOWN_INITIATED_BY_PEER:
            case QUIC_CONNECTION_EVENT_SHUTDOWN_COMPLETE: {
                self->shut.store(true, std::memory_order_relaxed);
                const std::lock_guard lock(self->m);
                self->handshake_done = true;
                self->cv.notify_all();
                return QUIC_STATUS_SUCCESS;
            }
            default:
                return QUIC_STATUS_SUCCESS;
        }
    }

    static QUIC_STATUS QUIC_API stream_cb(HQUIC, void* ctx, QUIC_STREAM_EVENT* ev) {
        (void)ctx;
        if (ev->Type == QUIC_STREAM_EVENT_SEND_COMPLETE) {
            tsan_acquire(ev->SEND_COMPLETE.ClientContext);  // pairs with write()'s release
            delete static_cast<send_buf_t*>(ev->SEND_COMPLETE.ClientContext);
        }
        return QUIC_STATUS_SUCCESS;
    }

    explicit raw_quic_client_t(std::uint16_t port) {
        if (QUIC_FAILED(MsQuicOpen2(&api))) {
            api = nullptr;
            return;
        }
        const QUIC_REGISTRATION_CONFIG rc{"quic_test_raw", QUIC_EXECUTION_PROFILE_LOW_LATENCY};
        if (QUIC_FAILED(api->RegistrationOpen(&rc, &reg))) return;
        const QUIC_BUFFER alpn{sizeof("libtracer") - 1,
                               reinterpret_cast<uint8_t*>(const_cast<char*>("libtracer"))};
        QUIC_SETTINGS settings{};
        settings.IdleTimeoutMs = 0;
        settings.IsSet.IdleTimeoutMs = TRUE;
        if (QUIC_FAILED(
                api->ConfigurationOpen(reg, &alpn, 1, &settings, sizeof(settings), nullptr, &cfg)))
            return;
        QUIC_CREDENTIAL_CONFIG cred{};
        cred.Type = QUIC_CREDENTIAL_TYPE_NONE;
        cred.Flags = static_cast<QUIC_CREDENTIAL_FLAGS>(
            QUIC_CREDENTIAL_FLAG_CLIENT | QUIC_CREDENTIAL_FLAG_NO_CERTIFICATE_VALIDATION);
        if (QUIC_FAILED(api->ConfigurationLoadCredential(cfg, &cred))) return;
        if (QUIC_FAILED(api->ConnectionOpen(reg, &conn_cb, this, &conn))) {
            conn = nullptr;
            return;
        }
        tsan_release(this);  // publish the constructed client to its callbacks
        if (QUIC_FAILED(
                api->ConnectionStart(conn, cfg, QUIC_ADDRESS_FAMILY_UNSPEC, "127.0.0.1", port)))
            return;
        {
            std::unique_lock lock(m);
            cv.wait_for(lock, 5s, [this] { return handshake_done; });
            if (!handshake_ok) return;
        }
        if (QUIC_FAILED(
                api->StreamOpen(conn, QUIC_STREAM_OPEN_FLAG_NONE, &stream_cb, this, &stream))) {
            stream = nullptr;
            return;
        }
        if (QUIC_FAILED(api->StreamStart(stream, QUIC_STREAM_START_FLAG_NONE))) return;
        ok = true;
    }

    ~raw_quic_client_t() {
        if (api == nullptr) return;
        if (stream != nullptr) api->StreamClose(stream);
        if (conn != nullptr) {
            api->ConnectionShutdown(conn, QUIC_CONNECTION_SHUTDOWN_FLAG_NONE, 0);
            api->ConnectionClose(conn);
        }
        if (cfg != nullptr) api->ConfigurationClose(cfg);
        if (reg != nullptr) api->RegistrationClose(reg);
        MsQuicClose(api);
        tsan_acquire(this);  // all callbacks drained — take their published writes
    }

    // Write raw stream bytes (no framing added) in ONE StreamSend.
    void write(std::span<const std::byte> bytes) {
        auto* sb = new send_buf_t{};
        sb->bytes.assign(bytes.begin(), bytes.end());
        sb->buf.Length = static_cast<std::uint32_t>(sb->bytes.size());
        sb->buf.Buffer = reinterpret_cast<uint8_t*>(sb->bytes.data());
        tsan_release(sb);  // pairs with SEND_COMPLETE's acquire
        if (QUIC_FAILED(api->StreamSend(stream, &sb->buf, 1, QUIC_SEND_FLAG_NONE, sb))) delete sb;
    }

    [[nodiscard]] bool wait_shutdown(std::chrono::milliseconds budget) {
        const auto deadline = std::chrono::steady_clock::now() + budget;
        while (!shut.load(std::memory_order_relaxed)) {
            if (std::chrono::steady_clock::now() > deadline) return false;
            std::this_thread::sleep_for(5ms);
        }
        return true;
    }
};

// One length-prefixed record: u32-LE len ++ payload (the shared M6 framing).
std::vector<std::byte> record(std::span<const std::byte> payload) {
    std::vector<std::byte> out;
    tr::detail::append_le(out, static_cast<std::uint32_t>(payload.size()));
    out.insert(out.end(), payload.begin(), payload.end());
    return out;
}

std::vector<std::byte> test_frame(std::size_t len, std::uint8_t seed) {
    std::vector<std::byte> f(len);
    for (std::size_t i = 0; i < len; ++i) f[i] = static_cast<std::byte>(seed + i);
    return f;
}

void test_raw_frame_duplex() {
    std::printf("QUIC transport — raw frames both ways over localhost:\n");
    quic_transport_t listener(std::uint16_t{0}, g_cert, g_key);
    check(listener.ok(), "listener started (ephemeral port, dev cert)");
    quic_transport_t dialer("127.0.0.1", listener.local_port(), dev_tls());
    check(dialer.ok(), "dialer completed the QUIC handshake (insecure dev mode)");
    check(dialer.link_up(), "dialer reports link up (CONNECTED)");

    sink_t at_listener, at_dialer;
    listener.set_receiver([&](std::span<const std::byte> f) { at_listener.push(f); });
    dialer.set_receiver([&](std::span<const std::byte> f) { at_dialer.push(f); });

    const auto f1 = test_frame(5, 0x10);
    dialer.send(f1);
    check(at_listener.wait_for_count(1, 3000ms), "dialer->listener frame received");
    check(at_listener.count() == 1 && at_listener.at(0) == f1, "received bytes are identical");

    // The reply direction: the listener sends on the peer-started stream.
    const auto f2 = test_frame(9, 0x40);
    listener.send(f2);
    check(at_dialer.wait_for_count(1, 3000ms), "listener->dialer frame received");
    check(at_dialer.count() == 1 && at_dialer.at(0) == f2, "reply bytes are identical");
}

void test_split_and_coalesced() {
    std::printf("QUIC transport — split sends reassemble, coalesced sends split:\n");
    quic_transport_t listener(std::uint16_t{0}, g_cert, g_key);
    sink_t sink;
    listener.set_receiver([&](std::span<const std::byte> f) { sink.push(f); });

    raw_quic_client_t client(listener.local_port());
    check(client.ok, "raw msquic client connected");

    // One frame deliberately split across MANY StreamSends — the prefix one
    // byte at a time, the body in two pieces, with pauses so each rides its own
    // QUIC packet (RECEIVE-chunk reassembly across every boundary).
    const auto f1 = test_frame(64, 0x01);
    const auto r1 = record(f1);
    for (std::size_t i = 0; i < 4; ++i) {
        client.write(std::span(r1).subspan(i, 1));
        std::this_thread::sleep_for(20ms);
    }
    client.write(std::span(r1).subspan(4, 10));
    std::this_thread::sleep_for(20ms);
    client.write(std::span(r1).subspan(14));
    check(sink.wait_for_count(1, 3000ms), "split frame reassembled into ONE delivery");
    check(sink.count() == 1 && sink.at(0) == f1, "reassembled bytes are identical");

    // Two complete records coalesced into ONE StreamSend — the reassembler must
    // honor the record boundaries and deliver two frames.
    const auto f2 = test_frame(7, 0x60);
    const auto f3 = test_frame(31, 0x90);
    std::vector<std::byte> both = record(f2);
    const auto r3 = record(f3);
    both.insert(both.end(), r3.begin(), r3.end());
    client.write(both);
    check(sink.wait_for_count(3, 3000ms), "coalesced send delivered as TWO frames");
    check(sink.count() == 3 && sink.at(1) == f2 && sink.at(2) == f3,
          "record boundaries honored (both frames byte-identical)");
}

void test_big_frame_chunking() {
    std::printf("QUIC transport — a big frame arrives through many RECEIVE chunks:\n");
    quic_transport_t listener(std::uint16_t{0}, g_cert, g_key);
    sink_t sink;
    listener.set_receiver([&](std::span<const std::byte> f) { sink.push(f); });
    quic_transport_t dialer("127.0.0.1", listener.local_port(), dev_tls());

    // ~300 KiB spans hundreds of QUIC packets — msquic MUST deliver it in
    // multiple RECEIVE chunks, exercising body reassembly at scale; the small
    // frames around it prove the framing state machine re-arms cleanly.
    const auto small1 = test_frame(3, 0x07);
    const auto big = test_frame(300 * 1024, 0x11);
    const auto small2 = test_frame(11, 0xC0);
    dialer.send(small1);
    dialer.send(big);
    dialer.send(small2);

    check(sink.wait_for_count(3, 5000ms), "all three frames delivered");
    check(sink.count() == 3 && sink.at(0) == small1, "small frame before the big one intact");
    check(sink.count() == 3 && sink.at(1) == big, "300 KiB frame byte-identical (reassembled)");
    check(sink.count() == 3 && sink.at(2) == small2, "small frame after the big one intact");
}

void test_oversize_prefix() {
    std::printf("QUIC transport — an oversize length prefix is malformed:\n");
    quic_transport_t listener(std::uint16_t{0}, g_cert, g_key);
    std::atomic<int> delivered{0};
    listener.set_receiver([&](std::span<const std::byte>) { delivered.fetch_add(1); });

    raw_quic_client_t client(listener.local_port());
    check(client.ok, "raw msquic client connected");
    std::vector<std::byte> prefix;
    tr::detail::append_le(prefix, static_cast<std::uint32_t>(quic_transport_t::kMaxFrame + 1));
    client.write(prefix);

    const auto deadline = std::chrono::steady_clock::now() + 3s;
    while (listener.malformed_rx() == 0 && std::chrono::steady_clock::now() < deadline)
        std::this_thread::sleep_for(5ms);
    check(listener.malformed_rx() == 1, "the oversize prefix counted as malformed");
    check(delivered.load() == 0, "nothing delivered");
    // A desynced stream cannot be re-framed — the transport shuts the
    // connection down, observable as a shutdown event at the client.
    check(client.wait_shutdown(3000ms), "the connection was torn down (peer saw shutdown)");
}

// A heap-delegating backend that RECORDS every segment it hands out (segment
// identity) and can FAIL its first `fail_first` allocations (backpressure).
class recording_backend_t final : public tr::mem::mem_backend_t {
   public:
    explicit recording_backend_t(int fail_first = 0)
        : mem_backend_t("rec_heap"), fail_remaining_(fail_first) {}

    tr::view::segment_t* alloc(std::size_t size,
                               tr::mem::alloc_hint_t hint = tr::mem::alloc_hint_t::NONE) override {
        if (fail_remaining_.fetch_sub(1, std::memory_order_relaxed) > 0) return nullptr;
        tr::view::segment_t* const seg = tr::mem::heap_backend().alloc(size, hint);
        if (seg != nullptr) {
            const std::lock_guard lock(m_);
            segments_.push_back(seg);
        }
        return seg;
    }
    void destroy(tr::view::segment_t* seg) noexcept override {
        tr::mem::heap_backend().destroy(seg);
    }

    [[nodiscard]] std::vector<tr::view::segment_t*> segments() const {
        const std::lock_guard lock(m_);
        return segments_;
    }

   private:
    std::atomic<int> fail_remaining_;
    mutable std::mutex m_;
    std::vector<tr::view::segment_t*> segments_;
};

// ADR-0042 — the owning delivery path: an installed view receiver gets each
// frame as a view over a fresh refcounted segment from the injected backend,
// allocated at exactly the frame length (the prefix announces `len` up front).
void test_view_delivery_segment_identity() {
    std::printf("QUIC transport — owning view delivery (ADR-0042 receiver seam):\n");
    recording_backend_t rec;
    quic_transport_t listener(std::uint16_t{0}, g_cert, g_key, &rec);
    check(listener.delivers_ropes(), "quic_transport_t::delivers_ropes() is true");
    quic_transport_t dialer("127.0.0.1", listener.local_port(), dev_tls());

    std::promise<tr::view::view_t> got;
    auto fut = got.get_future();
    listener.set_rope_receiver([&](tr::view::rope_t f) {
        if (f.link_count() == 1) got.set_value(f.links()[0]);  // single-link: the trivial rope
    });

    const auto frame = test_frame(48, 0x21);
    dialer.send(frame);

    const bool arrived = fut.wait_for(3s) == std::future_status::ready;
    check(arrived, "owning frame received on the peer");
    if (arrived) {
        const tr::view::view_t v = fut.get();
        check(static_cast<bool>(v.owner), "frame view OWNS a refcounted segment");
        const auto bytes = v.bytes();
        check(bytes.size() == frame.size() &&
                  std::memcmp(bytes.data(), frame.data(), frame.size()) == 0,
              "owning frame bytes are identical");
        const auto segs = rec.segments();
        check(!segs.empty() && v.owner.get() == segs.front(),
              "the frame segment IS the backend's segment (one copy off the msquic chunks)");
        check(v.owner && v.owner->bytes.size() == frame.size(),
              "the segment was allocated at exactly the frame length");
        check(v.owner.use_count() == 1, "the receiver holds the ONLY reference (no library copy)");
    }
    check(listener.dropped_rx() == 0, "no backpressure drops on the heap backend");
}

// ADR-0042 §2 backpressure on a stream: an exhausted backend drops the frame
// but SKIPS its bytes, so framing sync survives and later frames deliver.
void test_backpressure_drain() {
    std::printf("QUIC transport — backend exhaustion drains the frame, sync survives:\n");
    recording_backend_t rec(2);  // the first two allocations fail
    quic_transport_t listener(std::uint16_t{0}, g_cert, g_key, &rec);
    sink_t sink;
    listener.set_rope_receiver([&](tr::view::rope_t f) { sink.push(f.links()[0].bytes()); });
    quic_transport_t dialer("127.0.0.1", listener.local_port(), dev_tls());

    const auto f1 = test_frame(8192, 0x01);  // spans several RECEIVE chunks while draining
    const auto f2 = test_frame(16, 0x50);
    const auto f3 = test_frame(24, 0xA0);
    dialer.send(f1);
    dialer.send(f2);
    dialer.send(f3);

    check(sink.wait_for_count(1, 4000ms), "the third frame still delivers after two drops");
    check(listener.dropped_rx() == 2, "both exhausted frames counted as backpressure drops");
    check(sink.count() == 1 && sink.at(0) == f3,
          "framing sync survived the drained frames (byte-identical delivery)");
    check(listener.malformed_rx() == 0, "no malformed prefixes — the stream never desynced");
}

void test_scatter_gather() {
    std::printf("QUIC transport — scatter-gather send (rope -> one record, one gather copy):\n");
    quic_transport_t listener(std::uint16_t{0}, g_cert, g_key);
    sink_t sink;
    listener.set_receiver([&](std::span<const std::byte> f) { sink.push(f); });
    quic_transport_t dialer("127.0.0.1", listener.local_port(), dev_tls());

    const std::array<std::byte, 2> s0{std::byte{0x01}, std::byte{0x02}};
    const std::array<std::byte, 3> s1{std::byte{0x03}, std::byte{0x04}, std::byte{0x05}};
    const std::array<std::byte, 1> s2{std::byte{0x06}};
    const std::array<std::span<const std::byte>, 3> iov{std::span<const std::byte>(s0),
                                                        std::span<const std::byte>(s1),
                                                        std::span<const std::byte>(s2)};
    dialer.send(std::span<const std::span<const std::byte>>(iov));

    const std::array<std::byte, 6> expect{std::byte{0x01}, std::byte{0x02}, std::byte{0x03},
                                          std::byte{0x04}, std::byte{0x05}, std::byte{0x06}};
    check(sink.wait_for_count(1, 3000ms), "scatter-gather frame received");
    check(sink.count() == 1 && sink.at(0).size() == 6 &&
              std::memcmp(sink.at(0).data(), expect.data(), 6) == 0,
          "gathered segments arrive concatenated as one frame");
}

// Build FWD{ op=WRITE, dst=<segs...>, src=<empty PATH>, payload=<VALUE> } — a remote
// write routed by explicit source route (RFC-0004 §D, ADR-0040).
std::vector<std::byte> fwd_write(std::initializer_list<std::string_view> dst,
                                 std::span<const std::byte> payload_value_tlv) {
    std::vector<std::byte> body;
    const std::byte op{static_cast<std::uint8_t>(tr::graph::fwd_op_t::WRITE)};
    tr::wire::emit_tlv(body, type_t::VALUE, opt_t{}, std::span<const std::byte>(&op, 1));
    std::vector<std::byte> dst_segs;
    for (std::string_view s : dst) tr::wire::emit_name(dst_segs, s);
    tr::wire::emit_tlv(body, type_t::PATH, opt_t{.pl = true}, dst_segs);
    tr::wire::emit_tlv(body, type_t::PATH, opt_t{.pl = true},
                       std::span<const std::byte>{});  // src: empty, grows per hop
    body.insert(body.end(), payload_value_tlv.begin(), payload_value_tlv.end());
    std::vector<std::byte> frame;
    tr::wire::emit_tlv(frame, type_t::FWD, opt_t{.pl = true}, body);
    return frame;
}

// FWD{ op=READ, dst, src } — a remote read whose REPLY source-routes back.
std::vector<std::byte> fwd_read(std::initializer_list<std::string_view> dst,
                                std::initializer_list<std::string_view> src) {
    std::vector<std::byte> body;
    const std::byte op{static_cast<std::uint8_t>(tr::graph::fwd_op_t::READ)};
    tr::wire::emit_tlv(body, type_t::VALUE, opt_t{}, std::span<const std::byte>(&op, 1));
    std::vector<std::byte> dst_segs;
    for (std::string_view s : dst) tr::wire::emit_name(dst_segs, s);
    tr::wire::emit_tlv(body, type_t::PATH, opt_t{.pl = true}, dst_segs);
    std::vector<std::byte> src_segs;
    for (std::string_view s : src) tr::wire::emit_name(src_segs, s);
    tr::wire::emit_tlv(body, type_t::PATH, opt_t{.pl = true}, src_segs);
    std::vector<std::byte> frame;
    tr::wire::emit_tlv(frame, type_t::FWD, opt_t{.pl = true}, body);
    return frame;
}

void test_two_nodes_over_quic() {
    std::printf("Two nodes over QUIC — FWD delivery through fwd_router_t (ADR-0040):\n");
    // Declaration order matters: the transports are declared AFTER the routers
    // so they destruct FIRST — ~quic_transport_t drains msquic callbacks, so no
    // inbound frame can reach a router's child_registry_t after the router is gone.
    graph_t node_a, node_b;
    tr::net::fwd_router_t router_a(node_a);
    tr::net::fwd_router_t router_b(node_b);
    quic_transport_t tb(std::uint16_t{0}, g_cert, g_key);  // B listens (dev cert)
    quic_transport_t ta("127.0.0.1", tb.local_port(), dev_tls());

    // B holds the target vertex and a subscriber; A knows the link to B as "b".
    (void)node_b.register_vertex(path_t("/sensor/temp"), role_t::STORED_VALUE);
    router_a.add_child("b", ta);  // A routes a `dst` starting with "b" out over QUIC to B
    router_b.add_child("a", tb);  // B's name for the inbound link (src accumulation)

    std::promise<std::vector<std::byte>> got;
    auto fut = got.get_future();
    (void)node_b.subscribe(path_t("/sensor/temp"), [&got](const tr::view::rope_t& v) {
        const auto b = v.only().bytes();
        got.set_value(std::vector<std::byte>(b.begin(), b.end()));
    });

    std::vector<std::byte> payload;
    const std::array<std::byte, 2> pv{std::byte{0x2A}, std::byte{0x2B}};
    tr::wire::emit_tlv(payload, type_t::VALUE, opt_t{}, pv);
    const auto frame = fwd_write({"b", "sensor", "temp"}, payload);
    router_a.on_frame("client", frame);

    const bool arrived = fut.wait_for(4s) == std::future_status::ready;
    check(arrived, "node B receives the FWD-delivered value over real QUIC");
    if (arrived) {
        const auto r = fut.get();
        check(r.size() == payload.size() && std::memcmp(r.data(), payload.data(), r.size()) == 0,
              "delivered TLV bytes match across the wire (explicit source route)");
    }
}

view_t owned(std::span<const std::byte> bytes) {
    tr::view::segment_ptr_t seg = tr::view::heap_alloc(bytes.size());
    if (!bytes.empty()) std::memcpy(seg->bytes.data(), bytes.data(), bytes.size());
    return view_t::over(std::move(seg));
}

// SPEC{ NAME "type" <type>, NAME "name" <name>, SETTINGS "config"{ role, port,
// kind=quic [, addr] [, cert, key] } } — the tcp_test conn_spec shape plus the
// TLS-carrying `cert`/`key` config keys the quic LISTEN factory requires.
view_t conn_spec(std::string_view type, std::string_view name, tr::net::conn_role_t role,
                 std::uint16_t port, std::string_view addr = {}, std::string_view cert = {},
                 std::string_view key = {}) {
    std::vector<std::byte> cfg;
    tr::wire::emit_name(cfg, "role");
    const std::byte r{static_cast<std::uint8_t>(role)};
    tr::wire::emit_tlv(cfg, type_t::VALUE, opt_t{}, std::span<const std::byte>(&r, 1));
    tr::wire::emit_name(cfg, "port");
    std::vector<std::byte> pb(2);
    tr::detail::store_le(pb, port, 2);
    tr::wire::emit_tlv(cfg, type_t::VALUE, opt_t{}, pb);
    tr::wire::emit_name(cfg, "kind");
    tr::wire::emit_name(cfg, "quic");
    if (!addr.empty()) {
        tr::wire::emit_name(cfg, "addr");
        tr::wire::emit_name(cfg, addr);
    }
    if (!cert.empty()) {
        tr::wire::emit_name(cfg, "cert");
        tr::wire::emit_name(cfg, cert);
        tr::wire::emit_name(cfg, "key");
        tr::wire::emit_name(cfg, key);
    }

    std::vector<std::byte> body;
    tr::wire::emit_name(body, "type");
    tr::wire::emit_name(body, type);
    tr::wire::emit_name(body, "name");
    tr::wire::emit_name(body, name);
    tr::wire::emit_name(body, "config");
    tr::wire::emit_tlv(body, type_t::SETTINGS, opt_t{.pl = true}, cfg);

    std::vector<std::byte> out;
    tr::wire::emit_tlv(out, type_t::SPEC, opt_t{.pl = true}, body);
    return owned(out);
}

void test_config_constructed_quic() {
    std::printf("Config-constructed sockets: two nodes over QUIC from :children[] SPECs:\n");
    graph_t node_a;
    graph_t node_b;
    tr::net::fwd_router_t router_a(node_a);
    tr::net::fwd_router_t router_b(node_b);
    tr::net::transport_vertex_t net_a(node_a, router_a);
    tr::net::transport_vertex_t net_b(node_b, router_b);
    // The module plugs into the catalog through the extension seam — the core has
    // no `quic` builtin; a host that talks QUIC registers the factory at setup.
    net_a.register_transport_type("quic", tr::net::quic_transport_factory());
    net_b.register_transport_type("quic", tr::net::quic_transport_factory());

    std::promise<std::vector<std::byte>> got;
    auto fut = got.get_future();
    router_a.on_reply([&got](const tr::view::rope_t& reply) {
        try {
            const tr::view::view_t mat = reply.materialize();
            const auto b = mat.bytes();
            got.set_value(std::vector<std::byte>(b.begin(), b.end()));
        } catch (...) {
        }
    });

    // B: a stored value at /temp and a quic LISTENER on a fixed localhost port,
    // its dev cert/key handed in as `cert`/`key` config keys.
    (void)node_b.register_vertex(path_t("/temp"), role_t::STORED_VALUE);
    std::vector<std::byte> tv;
    const std::byte tb{0x2A};
    tr::wire::emit_tlv(tv, type_t::VALUE, opt_t{}, std::span<const std::byte>(&tb, 1));
    (void)node_b.write(path_t("/temp"), owned(tv));
    const auto wb = node_b.write(
        path_t("/net:children[]"),
        conn_spec("listener", "a", tr::net::conn_role_t::LISTEN, 47131, {}, g_cert, g_key));
    check(wb.has_value(), "B: SPEC{listener, kind=quic, port, cert, key} constructs the listener");
    check(router_b.registry().by_name("a") != nullptr, "B: the socket is wired into the router");

    // A missing cert/key on a quic LISTEN is a TYPE_MISMATCH (the kind requires them).
    const auto bad = node_b.write(path_t("/net:children[]"),
                                  conn_spec("listener", "bad", tr::net::conn_role_t::LISTEN, 0));
    check(!bad.has_value(), "B: a quic listener without cert/key fails creation");

    // A: a quic CLIENT dialing B's port — a synchronous handshake from config
    // (the DEV-ONLY no-verify trust mode, documented on the factory).
    const auto wa =
        node_a.write(path_t("/net:children[]"),
                     conn_spec("client", "b", tr::net::conn_role_t::DIAL, 47131, "127.0.0.1"));
    check(wa.has_value(), "A: SPEC{client, kind=quic, addr, port} constructs the dialing socket");
    const auto* s = net_a.settings_of("b");
    check(s != nullptr && s->kind == "quic" && s->addr == "127.0.0.1" && s->port == 47131,
          "A: the parsed :settings carry kind/addr/port");

    // End-to-end: FWD{READ dst=/b/temp} from A crosses A's config-created stream
    // to B's terminus, and the REPLY source-routes back over the same connection.
    router_a.on_frame("self", fwd_read({"b", "temp"}, {"reply-ep"}));
    const bool replied = fut.wait_for(4s) == std::future_status::ready;
    check(replied, "the READ reached B and the REPLY returned over the accepted peer");
    if (replied) {
        const std::vector<std::byte> reply_bytes = fut.get();  // owns; decode borrows
        const auto dec = tr::wire::decode(reply_bytes);
        bool has_value = false;
        if (dec && dec->type == type_t::FWD)
            for (const auto& c : dec->children)
                if (c.type == type_t::VALUE && c.payload.size() == 1 &&
                    c.payload[0] == std::byte{0x2A})
                    has_value = true;
        check(has_value, "the REPLY carries B's stored /temp value");
    }
}

}  // namespace

int main() {
    // Generate the self-signed dev pair once (tools/gen-dev-cert.sh) — the
    // LISTEN-side credential every test below serves.
    char tmpl[] = "/tmp/libtracer-quic-XXXXXX";
    const char* dir = ::mkdtemp(tmpl);
    if (dir == nullptr) {
        std::printf("FAIL: mkdtemp\n");
        return 1;
    }
    const std::string cmd = std::string("sh ") + LIBTRACER_DEV_CERT_SCRIPT + " " + dir;
    if (std::system(cmd.c_str()) != 0) {
        std::printf("FAIL: gen-dev-cert.sh\n");
        return 1;
    }
    g_cert = std::string(dir) + "/cert.pem";
    g_key = std::string(dir) + "/key.pem";

    test_raw_frame_duplex();
    test_split_and_coalesced();
    test_big_frame_chunking();
    test_oversize_prefix();
    test_view_delivery_segment_identity();
    test_backpressure_drain();
    test_scatter_gather();
    test_two_nodes_over_quic();
    test_config_constructed_quic();
    std::printf("\n%s (%d failure%s)\n", g_failures == 0 ? "ALL PASS" : "FAILURES", g_failures,
                g_failures == 1 ? "" : "s");
    return g_failures == 0 ? 0 : 1;
}
